### ISSUE TITLE
build failures on Ubuntu 20 / Rust 1.43.0

### ISSUE THREAD

**Issue by amalone-scwx** [redsift/ingraind#142]
I tried building both master and v1.0.0 branches and had some build failures.  Rustup show yields: `stable-x86_64-unknown-linux-gnu (default)
  rustc 1.43.0 (4fb7144ed 2020-04-20)`

A regular `cargo build --release` fails when building ingraind-probes with message 'NoOPT':
![ss-ingraind-build](https://user-images.githubusercontent.com/58046369/82348553-a5a34c80-99be-11ea-9a08-1f5bfae9fe77.png)

Any ideas?

**Comment by rsdy** [comment]
Hey! Sorry for the slow response on this, I was just able to take a look. You need LLVM 9, whereas Ubuntu 20.04 ships with LLVM 10 by default.

We are tracking the Rust stable, and once they move to LLVM 10, we will too.

**Comment by amalone-scwx** [comment]
thanks
