### ISSUE TITLE
Build error: use of unstable library feature 'matches_macro'

### ISSUE THREAD

**Issue by gbedoya** [redsift/ingraind#213]
Hi, I attempted to build from the master branch and came across the following error ...

```
   Compiling toml v0.5.6
   Compiling llvm-sys v100.2.0
error: No suitable version of LLVM was found system-wide or pointed
       to by LLVM_SYS_100_PREFIX.

       Consider using `llvmenv` to compile an appropriate copy of LLVM, and
       refer to the llvm-sys documentation for more information.

       llvm-sys: https://crates.io/crates/llvm-sys
       llvmenv: https://crates.io/crates/llvmenv
   --> /home/gbedoya/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-100.2.0/src/lib.rs:483:1
    |
483 | / std::compile_error!(concat!(
484 | |       "No suitable version of LLVM was found system-wide or pointed
485 | |        to by LLVM_SYS_", env!("CARGO_PKG_VERSION_MAJOR"), "_PREFIX.
486 | |
...   |
490 | |        llvm-sys: https://crates.io/crates/llvm-sys
491 | |        llvmenv: https://crates.io/crates/llvmenv"));
    | |____________________________________________________^

error: aborting due to previous error

error: could not compile `llvm-sys`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I manually downloaded **llvmenv** and added `$HOME/.cargo/bin` to my path.

Here's my llvm version ... 
```sudo apt show llvm
Package: llvm
Version: 1:7.0-47
Priority: optional
Section: devel
Source: llvm-defaults (0.47)
Maintainer: LLVM Packaging Team <pkg-llvm-team@lists.alioth.debian.org>
```

Am I missing a decency or using the wrong LLVM version?

**Comment by rsdy** [comment]
You will need LLVM 10 to compile ingraind. I think it's worth checking if Debian backports has the correct version, or using a container/chroot to set up the correct environment as documented [here](https://github.com/redsift/ingraind-build/blob/master/Dockerfile.20.04) for Ubuntu. Debian Sid should also certainly have the correct version.

**Comment by gbedoya** [comment]
Gotcha. I install LLVM10 using their Apt repositories here ...
https://apt.llvm.org/
However,

**Comment by rsdy** [comment]
Can you confirm the Rust version you're building with using `rustc -V`? I think a `rustup update` would probably fix this issue, but if you're using Rust from Debian stable, that will be quite outdated, as well.

**Comment by gbedoya** [comment]
I installed the additional **zlib1g-dev** decency as well for a successful build on rust 1.46.0
