### ISSUE TITLE
syscall probe question

### ISSUE THREAD

**Issue by jabedude** [redsift/ingraind#222]
Hello, I have a question about the syscall probe (ingraind-probes/src/syscalls/main.rs). Based on the code, it looks like it's supposed to capture all syscall events on a system but the probe is only placed on the `clone(2)` entry point (__x64_sys_clone). Am I misunderstanding the redbpf kprobe attribute? Thank you!

**Comment by rsdy** [comment]
In RedBPF you can choose to override where you want to bind the kprobes. This is what the [syscalls](https://github.com/redsift/ingraind/blob/master/src/grains/syscalls.rs#L38) grain does, it takes the monitored syscall names from the config and places a kprobe on each.

**Comment by jabedude** [comment]
Thank you @rsdy!
